### ISSUE TITLE
create projpoints function

### ISSUE THREAD

**Issue by rmaia** [rmaia/pavo#12]
because of the coordinate system, adding points is an issue.

even better: points.projplot ?

**Comment by celiason** [comment]
so you would create a projplot object first then add a layer? i guess this is kinda how the persp fxn works. makes sense i think.

**Comment by celiason** [comment]
also, would it make sense to add an argument that allows different transformations in projplot and/or ability to rotate the view?

**Comment by rmaia** [comment]
yes to the first comment.

not sure about the second. probably? what do you think?

**Comment by rmaia** [comment]
done? whodunnit?
