### ISSUE TITLE
Always return the lum column for vismodel

### ISSUE THREAD

**Issue by Bisaloo** [rmaia/pavo#135]
When I started using pavo, it took me some time to understand that vismodel would only have the `lum` column if I specified the `achromatic` argument.

Today, labmates told me they had the same issue.

I think it would make more sense to always return the `lum` column but just fill it with `NA` if no achromatic sensitivities have been passed.

What do you think?

This change in `vismodel()` might also require some changes to downstream functions such as `colspace()`

**Comment by thomased** [comment]
Yeah makes sense to me. That's what I (unconsciously) did with `adjacent` — always return the full possible output, just with NA's where the relevant input hasn't been provided.

**Comment by thomased** [comment]
Should be good
