### ISSUE TITLE
Feature request interp = FALSE for getspec() function

### ISSUE THREAD

**Issue by nitschkematthew** [rmaia/pavo#140]
First, thanks for pavo. Really enjoying putting this package to work!

I use the getspec() function quite frequently for importing many individual ocean optics text files. Perhaps as a feature/enhancement request, it would be useful to be able to set interp = FALSE when calling getspec() as some may find use for sub nm resolution. I notice that this is already implemented in as.rspec()?

**Comment by Bisaloo** [comment]
Hi @nitschkematthew! Thank you for reaching out!

As it happens, I was thinking about this recently. I can see how it would be useful but it's not that easy to implement. `getspec()` reads from a large variety of different file formats and concatenate them in a single dataframe.

For this to be possible, all spectra must be evaluated over the same wavelengths, which is not usually the case at first. So, we do need to interpolate them to make sure that they can safely be concatenated afterwards.

What we could maybe do however is offer the option to interpolate over a custom vector, say `seq(from = 300, to = 700, by = 0.1)`. This might help for the use case you are describing.

If you sure that all your spectra are evaluated over the same wavelengths and you really want `interp = FALSE`, your best bet is probably to import them individually in a custom loop and then `cbind` them yourself. That's not the easiest route but the [`lightr`](https://github.com/Bisaloo/lightr) package might be useful here.

Does this help? The other maintainers might have other ideas as well.

**Comment by nitschkematthew** [comment]
Thanks for the quick feedback @Bisaloo! Ah yes I see the problem. When aggregating data from multiple instruments you of course need to interpolate to output a single wl column in a dataframe.

However, I do think that single instrument studies where the wavelengths are equal file to file will be a fairly common use case.

Thanks for the help! I will also check out lightr.

**Comment by Bisaloo** [comment]
I drafted [a vignette on that topic](https://bisaloo.github.io/lightr/articles/custom_import.html). It's still very much a work in progress so any feedback is welcome but it may be able to get you started.

**Comment by Bisaloo** [comment]
@nitschkematthew, https://github.com/ropensci/lightr/commit/ec57fa966141fe0d107244fdb0718a6213a032e5 adds this feature to the development version of `lightr` (which you can install with `remotes::install_github("ropensci/lightr")`). It's still highly experimental so please let me know if you encounter any problems.

**Comment by Bisaloo** [comment]
Next steps:

- [ ] Make it work with `plot.rspec()`
- [ ] Make it work with `peakshape()` (https://github.com/rmaia/pavo/issues/19)

I'm not sure it would make sense to adapt other functions. Maybe simply ensure they have useful error messages (?).

**Comment by thomased** [comment]
That'd be my feeling. Everything's a tradeoff — we could spend the time, but unless there's some more demand for sub-nm plotting (which can be done manually easy enough anyway) and peakshape etc. I'd be inclined to pop in a useful message/error for now.

**Comment by Bisaloo** [comment]
I was wondering if uninterpolated spectral data should be considered as `rspec` at all. This would alleviate some of these issues since users would have to run `as.rspec()` (and interpolate the data) if they want to have `rspec` objects to work with `pavo`.

I'd simply be inclined to fix `plot.rspec()` since it shouldn't be to hard and having the ability to simply visualise spectra seems like a legitimate demand.

**Comment by thomased** [comment]
Yeah that's all a good idea. So am I right in imagining that if they use pavo's `getspec()` it'll be interpolated by necessity (since the output is always an `rspec` object), and if they want the raw raw stuff they'd need to use `lightr` directly, rather than via the `getspec()` wrapper. And we just document that option/pathway. (?).

How would `plot.rspec` see non-rspec objects though?

**Comment by Bisaloo** [comment]
Ah, `plot.rspec()` is already working fine. It was only upset by `NaN` and `Inf` values.

**Comment by Bisaloo** [comment]
> Yeah that's all a good idea. So am I right in imagining that if they use pavo's getspec() it'll be interpolated by necessity (since the output is always an rspec object), and if they want the raw raw stuff they'd need to use lightr directly, rather than via the getspec() wrapper. And we just document that option/pathway. (?).

Right, since my guess is that most `pavo` functions (e.g. vismodel()) will/should never work with non-integer `wl`. So it makes sense for `pavo` to only propose the `interpolate = TRUE` option.

> How would plot.rspec see non-rspec objects though?

Yeah, IDK. That's why I output `rspec` objects in all cases for now.

**Comment by Bisaloo** [comment]
Just to keep track. Even if we don't do any specific effort to get functions working with non-integer wl, it's still useful to know. Feel free to edit this message.

List of functions that work with non-integer wl:

- [x] `plot.rspec()`

List of functions with useful error messages:
