### ISSUE TITLE
weber.achro

### ISSUE THREAD

**Issue by Costa999** [rmaia/pavo#147]
Hi, I realized that it is possible to put weber.achro=TRUE. However, weber.achro is then calculated as if it was 1.0. I think it would be better if it was calculated as 0.1.
Thank you

**Comment by rmaia** [comment]
hi @Costa999 , in the help for the function, you'll see that `weber.achro` is a numeric argument. `R`'s behavior is to treat `TRUE` as `1` when a boolean is treated as numeric (and `FALSE` is `0`).  The `achro` argument is the one that requires a boolean input, so perhaps you're getting those two mixed up. By default, `weber.achro =0.1`. See `?coldist` for more info.
