### ISSUE TITLE
Return plots as objects

### ISSUE THREAD

**Issue by Bisaloo** [rmaia/pavo#149]
It would be convenient to be able to store plots in objects. This is useful when you want to run functions on your plots, such as functions from https://github.com/clauswilke/colorblindr.

Right now, you will get `NULL` if you try e.g. `test <- explorespec(sicalis, by = 3)`

**Comment by thomased** [comment]
Yeah it'd be cool, but isn't it a total pain (or impossible?) for base graphics since they draw directly on a device? Or are you thinking of a switch to a different graphics setup altogether?

**Comment by Bisaloo** [comment]
Arg, you're right. For some reason, I was convinced that base R plots were objects too. 

Huum, I'll keep thinking about it for a bit and close this issue if I don't find any satisfactory solution to do it.

**Comment by Bisaloo** [comment]
This is outside pavo's scope IMO but for future reference, it can be done with the `capturePlot()` function from the `R.devices` package.

https://cran.r-project.org/web/packages/R.devices/index.html
