### ISSUE TITLE
simulate spectra?

### ISSUE THREAD

**Issue by thomased** [rmaia/pavo#151]
I wonder if it'd be useful to be able to simulate spectra more generally. Assuming (very roughly) that most natural reflectances are some combination of sigmoids and bell-curves, it shouldn't be too tough to throw together a function that'd let your specify whatever combinations/shapes/locations of each to make some fake specs.

**Comment by Bisaloo** [comment]
The functions used in [this article](https://doi.org/10.1086/510138) might be a good basis.

For "yellow", "orange", "red", and "white" colours:

![](https://cdn.mathpix.com/snip/images/GGbJqQ3-bMYv8zZwMGPdK6QyPcBf243Eks6VjbFNL_o.original.fullsize.png)

For "green", "blue", and "violet" colours:

![](https://cdn.mathpix.com/snip/images/aN7RNtjkwbz4XVTtWsQ5QM5BL5ML7HRcu-um7_7g-Co.original.fullsize.png)
