### ISSUE TITLE
Only compute required variables in summary.rspec()

### ISSUE THREAD

**Issue by Bisaloo** [rmaia/pavo#165]
```r
library(pavo)
data(sicalis)
summary(sicalis, subset = "H1")
```

`summary.rspec()` will still compute all vars and only return H1, which seems like a waste of time and resources.

**Comment by thomased** [comment]
Yep, more generally:
- [ ] refactor to reduce unnecessary calculations for subsets, and just tidy up general messiness.
- [ ] make sure that everything that should work with an arbitrary wl range (including NIR), does so.
- [ ] add a new flexible S (?), and see if any other 'flexible' metrics might be appropriate
- [ ]  deprecate `wlmin` and `wlmax` for `lim` for consistency with other functions. We might also need a second `lim` or some way to specify two ranges, for the 'flexible S'.

**Comment by Bisaloo** [comment]
IMO, `summary.rspec()` should keep returning the vars it is returning now. These are 'standard' spectral shapes descriptors (Montgomerie 2006).

I believe the need for more unusual variables should be addressed by a new, separate, function, which would compute what you call the 'flexible S'.

This new function could then be re-used in `summary.rspec()` to compute all S1 vars.

This would also avoid a breaking change in the output format of `summary.rspec()`.

**Comment by thomased** [comment]
Yeah I can see that, but a new user-facing function for something so closely related to what `summary` does seems a bit heavy? I wasn't imagining breaking changes to `summary.rspec()`, unless I'm off the mark. It should still return everything it currently does, just a touch more flexibly so for whatever specified range that can extend into the NIR (which it basically already can & does, except for wl-specific variables like carotenoid chroma). 

Anything new could just be tacked on. E.g. the reflectance ratio of any two regions (flexible S) could just be `S11`, and take the two wl ranges via the reworked `lim = ` argument somehow.

**Comment by thomased** [comment]
Oh I just noticed you said 'output format' sorry. Yeah I suppose the full output format would be expanded with the addition of a new variable or two, but I guess I don't really thinking about that as 'breaking' so much (or not such a serious case anyway).
