### ISSUE TITLE
Returning negative qcatches

### ISSUE THREAD

**Issue by thomased** [rmaia/pavo#173]
Need to give some thought to handling the return of negative cone catches, which typically occurs when log-transforming values < 1 (which, in turn, often results from not using `scale` with relative illuminants like the built-ins). Users should be checking results of course, but a warning or message might be appropriate since the values are basically nonsense. Plus `coldist()` will still run fine and return (useless?) values without issue, though `boolcoldist()` errors uninformatively. E.g:

```
data(sicalis)
sicmod_fi <- vismodel(sicalis, qcatch = 'fi', relative = FALSE)

# Runs fine
coldist(sicmod_fi) 

# Errors unhelpfully
regions <- substr(rownames(sicmod), 6, 6)
bootcoldist(sicmod_fi, by = regions, n = c(1, 2, 2, 4), weber = 0.05) 
```

**Comment by thomased** [comment]
Roughed-in some warnings at 300b47747fa3e712de7708b52c19cce7202ef3bb & ce55616c6dab758c93527bed69b9a183d283b106. See what you think (could be messages? Or even hard-stops?...).

**Comment by Bisaloo** [comment]
Looks good to me!

**Comment by thomased** [comment]
c5cd8b3936ea1553378fcbe0b883d9e077942162 Should now only check columns containing quantum catch values (not x/y coords etc.) to avoid the spurious errors. Not sure how to robustly do it for BYO data that isn't named in a standard way, off the top of my head. Will have a think, but it's an edge-case anyway.

**Comment by Bisaloo** [comment]
Another option might be to put this warning at the end of `vismodel()`, in a similar way to what we do for `rspec` objects in `getspec()`. Not sure if that would make sense / be better.

The possible upside I see is that it would work for `cie` objects as well.

**Comment by thomased** [comment]
Yeah I already put it at the end of `vismodel()`, but now can't remember why I also stuck it in `coldist()`. Maybe just to be extra sure. But yeah it's probably redundant since I can't reliably check non-vismodel data anyway.
