### ISSUE TITLE
summary.tcs: include percent volume fill

### ISSUE THREAD

**Issue by rmaia** [rmaia/pavo#18]
```{r}
# Divide obtained color volume by:
 dat <- setNames(data.frame(diag(4)), c('u','s','m','l'))
 attr(dat, 'relative') <- TRUE
summary(tcs(dat))$c.vol
```

**Comment by rmaia** [comment]
I have no idea anymore what I meant by this when I added this.

**Comment by celiason** [comment]
You mean the percent volume fill part or the code chunk?

**Comment by rmaia** [comment]
either? both? how they're related? #HALP

**Comment by rmaia** [comment]
oh yeah I get it now. That's the volume for the entire tetrahedron. So dividing c.vol by that will give the relative color volume.

**Comment by rmaia** [comment]
done
