### ISSUE TITLE
Option for raw values in bootcoldist()?

### ISSUE THREAD

**Issue by thomased** [rmaia/pavo#194]
Consider returning raw values in `bootcoldist()`. Would have to be long format with a variable coding the patches being contrasted. Could think about adding `summary()` and/or `plot()` methods.

**Comment by thomased** [comment]
Added in 210b158c79d0ff8b04f09615c0da2d1b3e51c005, `bootcoldist()` now takes a `raw` argument to specify whether summary values or the full list of bootstrapped distances should be returned. 

Not sure about adding `summary` methods, since the means are calculated empirically. So unless users also supplied the raw data, the means returned by a `summary` method (based on the bootstrapped values) will never match the results returned by `bootcoldist(x, raw = FALSE)`. And plots — eh. Users can `hist()` or whatever they like easily enough. Not sure it's worth it either.

Ping @bittonp, just FYI. I _think_ you mentioned this would be a useful feature ages ago? Sorry it took so long!

**Comment by bittonp** [comment]
Thanks! It will be useful.
