### ISSUE TITLE
R CMD check --as-cran error on example("img_conversion")

### ISSUE THREAD

**Issue by HenrikBengtsson** [rmaia/pavo#197]
Hi. I'm running revdepcheck:s on {progressr} and spotted a potential issue with your package where I get check errors on [`example("img_conversion")](https://github.com/rmaia/pavo/blob/e8a7afda5aec720f25ebd09568bb41ed9eaef1b6/R/as.rimg.R#L198):

```r
> cleanEx()
> nameEx("img_conversion")
> ### * img_conversion
> 
> flush(stderr()); flush(stdout())
> 
> ### Name: img_conversion
> ### Title: Convert images between class rimg and cimg or magick-image
> ### Aliases: img_conversion rimg2cimg rimg2magick
> 
> ### ** Examples
> 
> papilio <- getimg(system.file("testdata/images/papilio.png", package = "pavo"))
> 
> # From class rimg to cimg
> papilio_cimg <- rimg2cimg(papilio)
Error: Package "imager" needed for conversion to cimg. Please install it.
Execution halted
```

Despite `\donttest{}`, I think this example needs to run conditionally on:

```r
if requireNamespace("imager", quiety=TRUE) {
   ...
}
```

You could hide that pre- and post- statement in a `\dontshow{}`

If {imager} would disappear from CRAN, then I think your package might fail the same way on CRAN too.

**Comment by HenrikBengtsson** [comment]
Forgot to say, this only happens when you check without {imager} installed.

**Comment by Bisaloo** [comment]
Thank you!

Note for future reference: it might be cleaner to use conditional examples when roxygen2 supports it (https://github.com/gaborcsardi/roxygenlabs#conditional-examples)
