### ISSUE TITLE
explorespec

### ISSUE THREAD

**Issue by celiason** [rmaia/pavo#20]
Explorespec without a value for 'by' gives same label for all subplots

**Comment by rmaia** [comment]
hmm I'm not having this problem? e.g.
![screen shot 2015-09-29 at 12 39 04 pm](https://cloud.githubusercontent.com/assets/1189223/10171244/1c0fb64c-66a7-11e5-8eed-ee88d8a7b3d0.png)

**Comment by bittonp** [comment]
I also do not have this problem. Was this something you experienced yourself or was it reported?

**Comment by celiason** [comment]
Try the revamp branch. I modified the code a while back to allow for grouping spectra by a factor (e.g., by=patch) rather than just a number. It happened after I made that change, so I can look into it.

**Comment by bittonp** [comment]
That's right... It uses the last name and applies it to all

**Comment by rmaia** [comment]
I think I fixed it, but please check
