### ISSUE TITLE
Slight fix test validation due to RNG update in upcoming future 1.21.0

### ISSUE THREAD

**Issue by HenrikBengtsson** [rmaia/pavo#212]
In future 1.21.0 there's a fix to the 'sequential' backend such that the RNG kind is preserved also in that case (just like for other types of backends), cf. https://github.com/HenrikBengtsson/future/issues/446

I'm posting this issue just for the record.  I'll following up with a PR shortly.

**Comment by HenrikBengtsson** [comment]
Hi, I'm hoping to submit future 1.21.0 to CRAN by the end of this week or so.  What's your plan for releasing the next version of **pavo**?  

If I submit before you, I need to figure out a way to work around the fact that the **pavo** checks will then fail and the patch here will probably not work and cause another error.  In other words, if you submit after me, there needs to be more coordination.  If you submit before me, things should work as-is.  In https://github.com/rmaia/pavo/issues/211#issuecomment-736774002 you hinted at you could release an updated **pavo** before next **future** release; would that be possible for you?

PS. If before submitting to CRAN, please make sure you also check against a recent devel version **future** 1.20.1-9000.

**Comment by thomased** [comment]
Hi,

Yeah sorry for the delay — we're planning a release very shortly. We need to do so before the 16th anyway as one of our Imports is being orphaned. But we've hit a small snag when making the necessary fix, and are just chasing down the cause atm. Once that's sorted it'll be off asap.

**Comment by HenrikBengtsson** [comment]
Ok, thanks for the update.   If you can, please give me a small heads up when you're getting closer so we're in sync and in case I decided to submit before you.

**Comment by thomased** [comment]
Hi again — I think we're all set on our end. I ran it against future 1.20.1-9000, no issues. 

Let me know if there's anything you need, otherwise we can ship it whenever ready.

**Comment by HenrikBengtsson** [comment]
Brilliant.  Let me run a quick check on my end too.  It's the pavo 'master' branch I should check against, correct?

**Comment by thomased** [comment]
Yep - that's the one. Much appreciated.

**Comment by HenrikBengtsson** [comment]
All good.  Validated on R 4.0.3 and latest R-devel on Linux.  Thanks for pushing this new version out.  Hoping it'll go smoothly for you.

**Comment by thomased** [comment]
Appreciate your help. It's submitted, so will hopefully be out soon.

**Comment by HenrikBengtsson** [comment]
> It's submitted, so will hopefully be out soon.

Did you submit it because it's nowhere to find under ftp://cran.r-project.org/incoming/?

**Comment by thomased** [comment]
Was a bit slow in checking my emails to confirm — should be on its way now.

<img width="768" alt="Screen Shot 2020-12-09 at 1 31 21 pm" src="https://user-images.githubusercontent.com/6053453/101566329-e75f1780-3a22-11eb-89b2-4dde2b29d5d3.png">

**Comment by HenrikBengtsson** [comment]
Perfect!

**Comment by HenrikBengtsson** [comment]
I see pavo ended up being [archived](https://cran.r-project.org/web/packages/pavo/) while your submitted pavo 2.6.0 still made it into the [archives](https://cran-archive.r-project.org/web/checks/2020/2020-12-09_check_results_pavo.html).  Hopefully, this is just a weird timing issue but if not, I guess it passed the incoming tests and the "someone" decided to drop you when other OS tests became available.  If so, I'm sorry about your struggles.

Just FYI, you don't have to worry about 'future' at this point, because if pavo makes it back on CRAN, I'm fine.  And if it remains archived, I'm also fine for my next release.

**Comment by thomased** [comment]
Yes, it made it through, then was archived ~12 hours later because it apparently creates `bin/phantomjs` in the home dir, which is a bit mysterious to me, but we'll get it figured out.

Glad to hear we're not holding up 'future' though — that's great.
