### ISSUE TITLE
Convert D65 to photon flux

### ISSUE THREAD

**Issue by thomased** [rmaia/pavo#215]
My fault, but a user noticed that our D65 is still in normalised radiant flux, rather than normalised photon flux. Think it crept in as part of #204 & I forgot to make the conversion. Should just need a `irrad2flux()` call & renormalisation in the data processing script.

**Comment by Bisaloo** [comment]
Might it be worth adding an attribute to record whether a rspec object is in irrad or flux (if we know)?

**Comment by thomased** [comment]
Yeah a `units` attribute would be a great idea - nice one.

**Comment by thomased** [comment]
Done for now. We'll add units as part of offloading the built-in data to its own package, which I'd like to get to this year.
