### ISSUE TITLE
procspec messages?

### ISSUE THREAD

**Issue by thomased** [rmaia/pavo#223]
Just scanning through the vignette & wondering if all the messages in `procspec()` are necessary any longer? I know it can be suppressed by users, but it seems like overkill to simply echo every option that a user selects (since the code itself documents what they've selected). Happy to hear thoughts, it's not a big issue.

```
data(flowers)
a <- procspec(flowers, opt = c('smooth', 'maximum', 'minimum', 'center'), fixneg = 'zero')
```

```
> a <- procspec(flowers, opt = c('smooth', 'maximum', 'minimum', 'center'), fixneg = 'zero')
processing options applied:
smoothing spectra with a span of 0.25
Negative value correction: converted negative values to zero
Scaling spectra to a minimum value of zero
Scaling spectra to a maximum value of 1
Centering spectra to a mean of zero
```

**Comment by Bisaloo** [comment]
Tough choice... If we were to write this function today, I would not include those messages. However, I am a bit reluctant to remove them now that users have gotten so accustomed to them.

**Comment by thomased** [comment]
Yeah good point, cheers.
