### ISSUE TITLE
replace sp point.in.polygon before October

### ISSUE THREAD

**Issue by thomased** [rmaia/pavo#252]
> library(pavo)
> 
> The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
> which was just loaded, will retire in October 2023.
> Please refer to R-spatial evolution reports for details, especially
> https://r-spatial.org/r/2023/05/15/evolution4.html.
> It may be desirable to make the sf package available;
> package maintainers should consider adding sf to Suggests:.
> The sp package is now running under evolution status 2
>      (status 2 uses the sf package in place of rgdal)

Only used here

https://github.com/rmaia/pavo/blob/347865f97ef7068211c29fb877799c4987830ac4/R/adjacent.R#L654

**Comment by Bisaloo** [comment]
One low dependency alternative could be https://r-spatial.github.io/s2/reference/s2_contains.html

**Comment by Bisaloo** [comment]
Upon testing s2, it appears that it works exclusively for geometry on a sphere and is therefore not appropriate for our use case.

Alternatives are:

- copying the relevant sp code
- copying code from https://stackoverflow.com/a/36684485/4439357
- using sf. I have a working solution but it's slightly slower and sf is slightly more dependency-heavy than sp

**Comment by thomased** [comment]
Ah right - thanks. I wouldn’t mind copying some code in the long run since it’s just to support that one tiny use, but I’m not up on weaving in cpp. 

How about just using the working solution you’ve got for now, and aiming for a neater solution next release? 

I’ve got some new features I’d like to get done, so release after this one should only be a 2-3 months.
