### ISSUE TITLE
spec2rgb broken on 'revamp'

### ISSUE THREAD

**Issue by thomased** [rmaia/pavo#30]
Just noticed I broke it - will fix. Something to do with the call to ciexyz, which I don't think exists as that anymore.

**Comment by rmaia** [comment]
fixed; broke because pavo:::ciexyz now has 6 columns (cie2 & cie10) and starts at 390 not 400. Currently using cie10, not sure what's best?

**Comment by thomased** [comment]
Yep - 10 degree is the more modern norm as I understand it. Not sure why I included 2. Why not I guess?
