### ISSUE TITLE
Can't combine plots with par() or layout()

### ISSUE THREAD

**Issue by thomased** [rmaia/pavo#41]
Noticed it in the tetra plots in the vignette, but seemingly applies to all plots. Something to do with new internal margin handling?

**Comment by thomased** [comment]
Actually it works for diplot(), which got the internal margin-handling revamp, but not for catplot(), which didn't.

**Comment by rmaia** [comment]
diplot() has internal parameter changes but catplot() doesn't? I don't know, but any way, I traced the problem to saving all parameters and recovering them on.exit(). I guess some parameters we don't want to save to be able to combine plots. So I changed it to be specific about what to save.
