### ISSUE TITLE
aggsplot Allow FUN.error that would generate non-symmetrical measure of variance

### ISSUE THREAD

**Issue by bittonp** [rmaia/pavo#48]
The current code only allows a calculation of 1 measure of variance per wavelength (call to aggspec) and then applies mean plus or minus variance. It would be useful to be able to plot based on non-symmetrical measures such as range or quantiles. When presenting ocular media transmission curves, for example, using SE or SD will give values above 100%. Using range would be more appropriate.

**Comment by rmaia** [comment]
I took a look at it, and I think that requires rewriting the aggspec function - either that or identifying that the error function would produce more than one output and calling both separately. 

Additionally, functions such as quantiles would require the exact value returned to be used in the plot, whereas other measures of dispersal are applied relative to the centering function. In other words, using quantile() would result in an output that goes directly into polygon(), whereas using sd() needs mean+sd to go into polygon().

not sure how to go about this one...

**Comment by rmaia** [comment]
`aggplot` now accepts `FUN.error` that would return two values, such as quantiles: https://github.com/rmaia/pavo/commit/91c7f81790884d331e47816fd91f9522c5d56294

It still can't tell if the values orbit around the mean or what to do if they don't (e.g. what if the user asks for quantiles 0.2, 0.4?). So if a single value is the result, it will add/subtract from the "mean" one, if two values is the result then it will just plot those. If more then two results it will fail.
