### ISSUE TITLE
provide an easy way to plot visual systems

### ISSUE THREAD

**Issue by rmaia** [rmaia/pavo#50]

**Comment by thomased** [comment]
Not sure if this is what you had in mind, but I threw in an idea as `sensdata()` (not a great name). It's basically a wrapper for pavo's in-built spectral data that lets users either plot or retrieve it. e.g.
```
sensdata(visual = c('avg.v', 'avg.uv'))
```
plots the average uv & v avian receptors, while
```
birds <- sensdata(visual = c('avg.v', 'avg.uv'), plot = FALSE)
```
assigns the combined spectra as an rspec object. It should be able to handle whatever combo:
```
sampler <- sensdata(visual = c('bluetit', 'pfowl'), achromatic = 'bt.dc', bkg = 'green', illum = c('bluesky', 'D65'), plot = FALSE)
``` 
Let me know if you think it might be useful anyway.

**Comment by rmaia** [comment]
😍
