### ISSUE TITLE
make a summary.segclass function?

### ISSUE THREAD

**Issue by rmaia** [rmaia/pavo#52]
make a function that calculates HSB based on Endler 1990, eqs 16 & 17?

**Comment by thomased** [comment]
Easy enough. segclass() feels kind of flabby now though (taking up its own dedicated class and functions). Plus I should probably make a little plot for it come to think of it (like Fig. 10 in Endler). Is it worth weaving it into the vismodel/colspace workflow? It is _kind of_ a 'colorspace' after all. For a user it could just look like: 

```
vismodel(spectra, visual = 'segment')  # with some messages that qcatch, illum etc. are being ignored
colspace(model, space = 'segment')
```
Then summary.colspace can give HSB, plot.colspace can make that odd little plot, coldist can be use for the Euc distances etc. Maybe?

**Comment by rmaia** [comment]
That's an excellent suggestion. vismodel could be just like segclass is now, and colspace could include HSB. plot could just plot LM ~ MS values, with a square defined by (1,0) (0,1) (-1,0) (0,-1)

**Comment by thomased** [comment]
Work in progress, but not far off.

- Merge segclass into vismodel & colspace #b9ab2510cbeec9c7f11753f15a14c5a6921f1f8d
- New segment plot #0ed64467600d95baba63a4aa2950635883a091b7

So this now works:
```
data(flowers)

# Old
oldseg <- segclass(flowers)

# New
visseg <- vismodel(flowers, visual = 'segment')
newseg <- colspace(visseg, space = 'segment')

# Eyeball the diffs. Slight variation I'm looking into.
head(oldseg)
head(newseg)

# Plot
plot(newseg)
```

There's a slight decimal-point difference between the old & new methods that I'm still tracking down. And I'll deprecate segclass() shortly.

**Comment by rmaia** [comment]
looking awesome! made a couple tweaks. We just need to figure out how to include B in the colspace result, which is not straightforward since input is standardized. Guess we could just hide the non-standardized it as an attribute?

**Comment by thomased** [comment]
Nice one. Yeah, forgot about B. Sneaky pass-through seems sensible? Nothing else springs to mind.

**Comment by rmaia** [comment]
Seems like the best way I can think. Only problem is if users import the segclass result already to just get the colspace and plot results. what are the odds of that ever actually happening...

**Comment by thomased** [comment]
Hah, I'm sure we'll find out. Maybe just throw 'we can't give you B' warning in for users bringing their own data.

**Comment by thomased** [comment]
Another possibility that occurred to me is forcing the use of the just-added `achromatic = 'all'` argument in segment analyses. So the user runs `vismodel()` and gets the four segments & lum, then `colspace()' to get the opponent axes and full CHB (B being lum renamed).

That's how it's set up at the moment, just so it's complete. Can also easily go with a quiet pass-through solution if that's preferable. No worries.

**Comment by thomased** [comment]
coldist integration - 31b4c89ab9ff7d8809ee4b594e535b03e7acfaad

**Comment by thomased** [comment]
Think this solution works nicely for now. Can always tweak the handling of B if that's an annoyance, but I suspect it's simpler to pass it around in the 'open' rather than using a dedicated hidden-attribute approach.
