### ISSUE TITLE
Human luminance

### ISSUE THREAD

**Issue by thomased** [rmaia/pavo#56]
Add vismodel() achromatic argument to sum response from all receptors (as in human vis for daylight luminance perception) & add human rod sensitivity function (for nocturnal human luminance) to built-in visual systems.

**Comment by thomased** [comment]
Added the 'all' option - c5470fceba9bf166c48e952da70a974a1af07101

**Comment by thomased** [comment]
Added lightness contrast for cielab output in coldist() - 3fcfb63c953b1f5522ba0e48880ccf59fdc3fcfd

**Comment by rmaia** [comment]
sounds like you've nailed this one too, so closing it unless you think it needs anything else
