### ISSUE TITLE
vismodel doesn't like monochromats

### ISSUE THREAD

**Issue by thomased** [rmaia/pavo#64]
```
data(flowers)
vismodel(flowers, visual = sensmodel(500))
```

**Comment by rmaia** [comment]
I guess for monochromats it should just use the achromatic formula?

**Comment by thomased** [comment]
Yeah, or should be equivalent anyway. I kinda almost had it running via the normal pathway, with a warning if achromatic is also selected (& a switch to 'none'), but am running into row/column naming issues. Just for reference:

Initial issue is monochromat sensitivity not being preserved as a data frame, fixed by 'drop': 
`S <- visual[, -which(names(visual)=='wl'), drop = FALSE]` (line 268)

then there's an issue with the chunk ~407, which was a fix for handling single reflectance spectra, but I think we can just ditch that since those new reference specs ensure there's never just a single spectrum by that point?:
```
#  if(dim(Qi)[1] < 2){
#    Qi <- data.frame(t(Qi))
#    rownames(Qi) <- names(y)
#  }
# names(Qi) <- names(S)
```

then the final (?) issues are around output row/column names and the new resref stuff, which is giving me the shits. Will have another look later on.
