### ISSUE TITLE
move distance functions inside coldist?

### ISSUE THREAD

**Issue by rmaia** [rmaia/pavo#65]
I'm getting annoyed that it's hard to test changes to `coldist` because of the calculation functions that are outside from it (because when any changes are sourced it can't find the functions not exported). I moved them into the function and renamed it `coldistWI` to see if it would change the speed at all. Doesn't seem like it does. Should we just move everything inside?

```
require('microbenchmark')
require('pavo')
data(flowers)
ss <- vismodel(flowers, achro=TRUE, relative=FALSE)
bm <- microbenchmark(old = coldist(ss), new = coldistWI(ss), times=100)
bm

Unit: milliseconds
 expr      min       lq     mean   median       uq      max neval
  old 107.8565 115.5273 121.5068 119.7694 124.2561 179.8979   100
  new 107.6310 116.1537 121.6796 121.3835 125.4255 174.2802   100
```

**Comment by thomased** [comment]
Yeah absolutely — sounds good. It'll prompt me to refactor some internal cruft too, I know there are near-duplicate distance measure of mine that could be combined.

**Comment by rmaia** [comment]
done
