### ISSUE TITLE
vismodel: add Stop if 'trans' is not a vector?

### ISSUE THREAD

**Issue by bittonp** [rmaia/pavo#72]
If 'trans' is an rspec object or 2 column matrix and 'rspecdata' has 3 columns (only 2 spectral curves), there are no warnings and the calculations are way off for the second curve. I would volunteer to fix this myself but I have not worked off github in a long time. I'll refresh my github knowledge and hope to contribute more soon.

**Comment by rmaia** [comment]
@bittonp can you post a reproducible example of the issue?

**Comment by rmaia** [comment]
fixed - https://github.com/rmaia/pavo/commit/e72e2d23e72fd5615924e37142567e787ee63429
