### ISSUE TITLE
issue reading ProcSpec

### ISSUE THREAD

**Issue by rmaia** [rmaia/pavo#81]
@Bisaloo a user is having trouble reading in this ProcSpec file, do you think you can debug it?

code used: `test <- getspec("/Desktop/test/", ext = “ProcSpec", decimal = "," )`

File is attached, please change extension to ProcSpec (github doesn't authorize uploading it).

Thanks!

[19-c.txt](https://github.com/rmaia/pavo/files/1644459/19-c.txt)

**Comment by Bisaloo** [comment]
That's interesting. The `xml` file contains a lot of information, including spectrometer firmware version. For some reason, the string with the firmware version in the example files has malformed characters.

I could reproduce this issue using python `libxml`. There is no proper fix as this is not a bug *per se* but #83 proposes a way to circumvent this kind of issue.
